# Generated by Django 5.0.4 on 2024-07-17 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('appointed', models.CharField(max_length=50)),
                ('hbpn', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlyAir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_employer', models.CharField(max_length=50)),
                ('visa_no', models.CharField(max_length=50)),
                ('visa_date', models.DateField(default=datetime.datetime.now)),
                ('name_employee', models.CharField(max_length=50)),
                ('passport_no', models.CharField(max_length=50)),
                ('passport_date', models.DateField(default=datetime.datetime.now)),
                ('profession', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visa_no', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=50)),
                ('dob', models.DateField(default=datetime.datetime.now)),
                ('pob', models.CharField(max_length=50)),
                ('prv_nationality', models.CharField(max_length=50)),
                ('prs_nationality', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('----', '----'), ('Male', 'Male'), ('Female', 'Female')], default='----', max_length=6)),
                ('marital_s', models.CharField(max_length=50)),
                ('sect', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('poi_1', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('home_add_and_tel_no', models.CharField(max_length=50)),
                ('bus_add_and_tel_no', models.CharField(max_length=50)),
                ('pot', models.CharField(choices=[('----', '----'), ('Work', 'Work'), ('Transit', 'Transit'), ('Visit', 'Visit'), ('Umrah', 'Umrah'), ('Residence', 'Residence'), ('Hajj', 'Hajj'), ('Diplomacy', 'Diplomacy')], default='----', max_length=10)),
                ('poi_2', models.CharField(max_length=50)),
                ('date_passport_issued', models.DateField(default=datetime.datetime.now)),
                ('passport_no', models.CharField(max_length=50)),
                ('date_passport_expiry', models.DateField(default=datetime.datetime.now)),
                ('dosK', models.IntegerField(default=0)),
                ('doa', models.DateField()),
                ('dod', models.DateField()),
                ('mode_of_payment', models.CharField(max_length=50)),
                ('Relationship', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('carriers_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VisaInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visa_qnt', models.IntegerField(default=0)),
                ('visa_no', models.CharField(max_length=50)),
                ('id_no', models.CharField(max_length=50)),
                ('visa_iss_dt', models.DateField(default=datetime.datetime.now)),
                ('submitted_date', models.DateField(default=datetime.datetime.now)),
                ('destination', models.CharField(max_length=50)),
                ('visa_person_name', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('thana', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=20)),
                ('post_office', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('sponser_name_english', models.CharField(max_length=50)),
                ('sponser_name_arabic', models.CharField(max_length=50)),
                ('sponser_phone', models.CharField(max_length=20)),
                ('sponser_address', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=50)),
                ('add_and_phone_no', models.CharField(max_length=20)),
            ],
        ),
    ]
