# Generated by Django 5.0.4 on 2024-07-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visaapplication',
            old_name='Qualification',
            new_name='qualification',
        ),
    ]
