# Generated by Django 5.0.4 on 2024-07-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0002_rename_qualification_visaapplication_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visaapplication',
            old_name='Relationship',
            new_name='relationship',
        ),
    ]
