# Generated by Django 5.0.4 on 2024-07-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0003_rename_relationship_visaapplication_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='photo',
            field=models.FileField(blank=True, default='studimage/blank.png', upload_to='studimage'),
        ),
    ]
