# Generated by Django 5.0.4 on 2024-07-17 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0004_visaapplication_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='doa',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='dod',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='dosK',
            field=models.CharField(max_length=50),
        ),
    ]
