# Generated by Django 5.0.7 on 2024-08-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0006_agreement_air_passage_agreement_duty_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='hbpn',
            field=models.CharField(max_length=50, verbose_name='Holder of Bangladesh Passport No'),
        ),
    ]
