# Generated by Django 5.0.7 on 2024-08-06 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0007_alter_agreement_hbpn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agreement',
        ),
        migrations.DeleteModel(
            name='FlyAir',
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='air_passage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='duty_hour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='food_and_accommodation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='holiday',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='leave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='medical_facilities',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='name_employer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='other_terms_and_conditions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='overtime_and_benefits',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='period_of_contract',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='repatriation_arrangement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='visa_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='bus_add_and_tel_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='carriers_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='date_passport_expiry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='date_passport_issued',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='destination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='doa',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='dod',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='dosK',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='f_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='home_add_and_tel_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='marital_s',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='passport_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='photo',
            field=models.FileField(blank=True, default='studimage/blank.png', null=True, upload_to='studimage'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='pob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='poi_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='poi_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='pot',
            field=models.CharField(blank=True, choices=[('----', '----'), ('Work', 'Work'), ('Transit', 'Transit'), ('Visit', 'Visit'), ('Umrah', 'Umrah'), ('Residence', 'Residence'), ('Hajj', 'Hajj'), ('Diplomacy', 'Diplomacy')], default='----', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='prs_nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='prv_nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='sect',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='sex',
            field=models.CharField(blank=True, choices=[('----', '----'), ('Male', 'Male'), ('Female', 'Female')], default='----', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='visa_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
