# Generated by Django 5.0.7 on 2024-08-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0008_delete_agreement_delete_flyair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='auth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
