# Generated by Django 5.0.7 on 2024-08-07 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0010_alter_visaapplication_pot'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='office_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='office_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='office_employer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='office_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='office_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='office_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
