# Generated by Django 5.0.7 on 2024-08-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0012_remove_visainfo_add_and_phone_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaapplication',
            name='air_passage',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='duty_hour',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='food_and_accommodation',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='medical_facilities',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='other_terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='overtime_and_benefits',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='period_of_contract',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='repatriation_arrangement',
        ),
    ]
