# Generated by Django 5.0.7 on 2024-08-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0013_remove_visaapplication_air_passage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='auth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
