# Generated by Django 5.0.7 on 2024-08-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0017_remove_visaapplication_mode_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='visa_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
