# Generated by Django 5.0.7 on 2024-08-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0019_alter_visainfo_visa_iss_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visainfo',
            name='id_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
