# Generated by Django 5.0.7 on 2024-08-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0020_alter_visainfo_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='visainfo',
            name='serial_id',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
