# Generated by Django 5.0.7 on 2024-08-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0021_visainfo_serial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visainfo',
            name='visa_qnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
