# Generated by Django 5.0.7 on 2024-08-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0022_alter_visainfo_visa_qnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='visainfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
