# Generated by Django 5.0.7 on 2024-08-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0024_visainfo_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visainfo',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
