# Generated by Django 5.0.7 on 2024-08-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0025_remove_visainfo_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visainfo',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
