# Generated by Django 5.0.7 on 2024-08-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0026_remove_visainfo_created_at_alter_visainfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.IntegerField(unique=True)),
                ('visa_qnt', models.IntegerField()),
                ('visa_no', models.CharField(max_length=50)),
            ],
        ),
    ]
