# Generated by Django 5.0.7 on 2024-08-10 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0027_broker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visainfo',
            old_name='id_no',
            new_name='sponser_id',
        ),
        migrations.RemoveField(
            model_name='visainfo',
            name='serial_id',
        ),
        migrations.RemoveField(
            model_name='visainfo',
            name='visa_no',
        ),
        migrations.RemoveField(
            model_name='visainfo',
            name='visa_qnt',
        ),
        migrations.AddField(
            model_name='visainfo',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uae_visa.broker'),
        ),
    ]
