# Generated by Django 5.0.7 on 2024-08-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0028_rename_id_no_visainfo_sponser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visainfo',
            name='serial_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
