# Generated by Django 5.0.7 on 2024-08-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0029_visainfo_serial_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visainfo',
            name='sponser_id',
        ),
    ]
