# Generated by Django 5.0.7 on 2024-08-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0030_remove_visainfo_sponser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visainfo',
            name='sponser_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
