# Generated by Django 5.0.7 on 2024-08-11 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0031_visainfo_sponser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visainfo',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='visa_no',
        ),
        migrations.RemoveField(
            model_name='visainfo',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='serial_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='visa_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uae_visa.visainfo'),
        ),
        migrations.AddField(
            model_name='visainfo',
            name='serial_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='visainfo',
            name='visa_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visainfo',
            name='visa_qnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='broker',
        ),
    ]
