# Generated by Django 5.0.7 on 2024-08-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0033_visaapplication_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visainfo',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
