# Generated by Django 5.0.7 on 2024-08-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0034_alter_visainfo_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visainfo',
            name='sponser_name_arabic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='sponser_name_english',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
