# Generated by Django 5.0.7 on 2024-08-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0035_alter_visainfo_sponser_name_arabic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='qualification',
            field=models.CharField(blank=True, default='CLASS EIGHT', max_length=50, null=True),
        ),
    ]
