# Generated by Django 5.0.7 on 2024-08-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0038_remove_visaapplication_carriers_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaapplication',
            name='bus_add_and_tel_no',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='poi_2',
        ),
    ]
