# Generated by Django 5.0.7 on 2024-08-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0039_remove_visaapplication_bus_add_and_tel_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaapplication',
            name='pob',
        ),
    ]
