# Generated by Django 5.0.7 on 2024-08-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0041_alter_visaapplication_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='auth',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
