# Generated by Django 5.0.7 on 2024-08-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0042_alter_visaapplication_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaapplication',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='office_date',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='office_duration',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='office_employer',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='office_fee',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='office_id',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='office_type',
        ),
    ]
