# Generated by Django 5.0.7 on 2024-08-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0043_remove_visaapplication_auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaapplication',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='name_employer',
        ),
        migrations.RemoveField(
            model_name='visaapplication',
            name='visa_date',
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='district',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='post_office',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='sender_address',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='sender_phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='sponser_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='sponser_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='sponser_name_arabic',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='sponser_name_english',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='sponser_phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='thana',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='village',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='visa_iss_dt',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='visa_person_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
