# Generated by Django 5.0.7 on 2024-08-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0044_remove_visaapplication_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='office_date',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='office_duration',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='office_fee',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='office_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
