# Generated by Django 5.0.7 on 2024-08-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uae_visa', '0045_visaapplication_office_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='doa',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='dob',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='dod',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visainfo',
            name='submitted_date',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
